[run]
init_cmds = [
  ["scripts/build.py","--clean","-v"],
	["./build/influxdb-relay", "-v", "-config", "./config/influxdb-relay.conf"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR",
]
watch_exts = [".go", ".toml"]
build_delay = 1500
cmds = [
  ["scripts/build.py","--clean","-v"],
	["./build/influxdb-relay","-v","-config","./config/influxdb-relay.conf"]
]
