[run]
init_cmds = [
  ["scripts/build.py","--clean","-v","--race"],
	["./build/influxdb-srelay", "-config", "./examples/influxdb-srelay.conf", "-logdir","./logs"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR",
]
watch_exts = [".go", ".toml"]
build_delay = 1500
cmds = [
  ["scripts/build.py","--clean","-v","--race"],
	["./build/influxdb-srelay","-config","./examples/influxdb-srelay.conf","-logdir","./logs"]
]
